#!/usr/bin/env python3
"""Generate the simple, dimensioned Gazebo rail model used by the demo."""

from __future__ import annotations

import argparse
from pathlib import Path


TRACK_LENGTH_M = 30.0
STANDARD_GAUGE_M = 1.435
RAIL_WIDTH_M = 0.07
RAIL_HEIGHT_M = 0.15
SLEEPER_LENGTH_M = 2.6
SLEEPER_WIDTH_M = 0.24
SLEEPER_HEIGHT_M = 0.16
SLEEPER_SPACING_M = 0.6
BALLAST_LENGTH_M = 32.0
BALLAST_WIDTH_M = 3.6
BALLAST_HEIGHT_M = 0.12

# Gauge is measured between the inner rail faces, not between rail centres.
RAIL_CENTER_OFFSET_M = (STANDARD_GAUGE_M + RAIL_WIDTH_M) / 2.0
SLEEPER_CENTER_Z_M = 0.16
RAIL_CENTER_Z_M = SLEEPER_CENTER_Z_M + SLEEPER_HEIGHT_M / 2.0 + RAIL_HEIGHT_M / 2.0
SLEEPER_COUNT = round(TRACK_LENGTH_M / SLEEPER_SPACING_M) + 1


def _box_collision(name: str, pose: str, size: str) -> str:
    return f"""      <collision name=\"{name}_collision\">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>"""


def _box_visual(
    name: str,
    pose: str,
    size: str,
    ambient: str,
    diffuse: str,
    specular: str,
) -> str:
    return f"""      <visual name=\"{name}_visual\">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>{ambient}</ambient>
          <diffuse>{diffuse}</diffuse>
          <specular>{specular}</specular>
        </material>
      </visual>"""


def build_track_model() -> str:
    elements = [
        _box_collision(
            "ballast",
            f"0 0 {BALLAST_HEIGHT_M / 2.0:.3f} 0 0 0",
            f"{BALLAST_LENGTH_M:.3f} {BALLAST_WIDTH_M:.3f} {BALLAST_HEIGHT_M:.3f}",
        ),
        _box_visual(
            "ballast",
            f"0 0 {BALLAST_HEIGHT_M / 2.0:.3f} 0 0 0",
            f"{BALLAST_LENGTH_M:.3f} {BALLAST_WIDTH_M:.3f} {BALLAST_HEIGHT_M:.3f}",
            "0.22 0.22 0.20 1",
            "0.32 0.31 0.28 1",
            "0.04 0.04 0.04 1",
        ),
    ]

    for index in range(SLEEPER_COUNT):
        x = -TRACK_LENGTH_M / 2.0 + index * SLEEPER_SPACING_M
        name = f"sleeper_{index:03d}"
        pose = f"{x:.3f} 0 {SLEEPER_CENTER_Z_M:.3f} 0 0 0"
        size = f"{SLEEPER_WIDTH_M:.3f} {SLEEPER_LENGTH_M:.3f} {SLEEPER_HEIGHT_M:.3f}"
        elements.extend(
            [
                _box_collision(name, pose, size),
                _box_visual(
                    name,
                    pose,
                    size,
                    "0.20 0.11 0.055 1",
                    "0.29 0.16 0.075 1",
                    "0.015 0.015 0.015 1",
                ),
            ]
        )

    for side, y in (("left", RAIL_CENTER_OFFSET_M), ("right", -RAIL_CENTER_OFFSET_M)):
        pose = f"0 {y:.4f} {RAIL_CENTER_Z_M:.3f} 0 0 0"
        size = f"{TRACK_LENGTH_M:.3f} {RAIL_WIDTH_M:.3f} {RAIL_HEIGHT_M:.3f}"
        elements.extend(
            [
                _box_collision(f"rail_{side}", pose, size),
                _box_visual(
                    f"rail_{side}",
                    pose,
                    size,
                    "0.24 0.25 0.27 1",
                    "0.42 0.44 0.48 1",
                    "0.70 0.70 0.72 1",
                ),
            ]
        )

    body = "\n".join(elements)
    return f"""<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!-- Generated by tools/generate_gazebo_rail_world.py. -->
<sdf version=\"1.9\">
  <model name=\"rail_track\">
    <static>true</static>
    <link name=\"track\">
{body}
    </link>
  </model>
</sdf>
"""


def build_world() -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<sdf version="1.9">
  <world name="rail_demo">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>
    <gravity>0 0 -9.8</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type="adiabatic"/>

    <scene>
      <grid>false</grid>
      <ambient>0.45 0.45 0.42 1</ambient>
      <background>0.70 0.78 0.86 1</background>
      <shadows>true</shadows>
    </scene>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>1 1</size></plane></geometry>
          <surface><friction><ode/></friction><bounce/><contact/></surface>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>200 100</size></plane></geometry>
          <material>
            <ambient>0.20 0.28 0.16 1</ambient>
            <diffuse>0.30 0.40 0.23 1</diffuse>
            <specular>0.02 0.02 0.02 1</specular>
          </material>
        </visual>
      </link>
    </model>

    <include>
      <uri>model://rail_track</uri>
      <name>main_track</name>
      <pose>0 0 0 0 0 0</pose>
    </include>

    <!-- A flat pad keeps the X500 away from rail collisions at startup. -->
    <model name="launch_pad">
      <static>true</static>
      <pose>-13 -3 0.06 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>3 3 0.12</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>3 3 0.12</size></box></geometry>
          <material>
            <ambient>0.28 0.28 0.28 1</ambient>
            <diffuse>0.38 0.38 0.38 1</diffuse>
            <specular>0.08 0.08 0.08 1</specular>
          </material>
        </visual>
      </link>
    </model>

    <light name="sunUTC" type="directional">
      <pose>0 0 500 0 0 0</pose>
      <cast_shadows>true</cast_shadows>
      <intensity>1</intensity>
      <direction>-0.25 0.45 -0.86</direction>
      <diffuse>0.92 0.90 0.84 1</diffuse>
      <specular>0.25 0.25 0.25 1</specular>
      <attenuation>
        <range>2000</range><linear>0</linear><constant>1</constant><quadratic>0</quadratic>
      </attenuation>
    </light>

    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>47.397971057728974</latitude_deg>
      <longitude_deg>8.546163739800146</longitude_deg>
      <elevation>0</elevation>
    </spherical_coordinates>
  </world>
</sdf>
"""


def output_files(repo_root: Path) -> dict[Path, str]:
    base = repo_root / "simulation" / "gazebo"
    return {
        base / "models" / "rail_track" / "model.sdf": build_track_model(),
        base / "worlds" / "rail_demo.sdf": build_world(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated files are missing or out of date",
    )
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[1]

    stale: list[Path] = []
    for path, expected in output_files(repo_root).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"generated {path.relative_to(repo_root)}")

    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(repo_root)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
